### ISSUE TITLE
Change Favicon Delivery Method

### ISSUE THREAD

**Issue by penguoir** [kingalfred/canvas#5]
Currently, [the favicon is changed](https://github.com/kingalfred/canvas/blob/4b2ff20d37b16c9238d7d8d6c40194ef00938a90/js/script.js#L103) to a [png hosted on imgur](https://i.imgur.com/DpAI7L4.png). This isn't an ideal method. We can change the favicon on the actual website by changing the `favicon.ico` file (once the server is added), or use built-in canvas theming to change the branding.

**Comment by lukafblepkowski** [comment]
Alright, when will the server be added

**Comment by conition** [comment]
We won't add the server anytime soon, as we need to figure everything out with Peter and the IT people first so we can properly set everything up.

**Comment by penguoir** [comment]
Fixed in 8cda13d0eac103ef08e4ad052a4b7da6a3693b06
